# Generated by Django 3.2.6 on 2021-08-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='admin_id',
            field=models.IntegerField(default=0, verbose_name='id админа(можно получить у @username_to_id_bot)'),
        ),
        migrations.AddField(
            model_name='buttonstext',
            name='replace_add_back_after',
            field=models.CharField(default='тест', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buttonstext',
            name='replace_add_back_before',
            field=models.CharField(default='тест', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buttonstext',
            name='replace_add_front_after',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buttonstext',
            name='replace_add_front_before',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buttonstext',
            name='replace_add_sideways_after',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buttonstext',
            name='replace_add_sideways_before',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marathon',
            name='count_users',
            field=models.IntegerField(default=0, verbose_name='Количество участников марафона'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='bot_token',
            field=models.CharField(default='', max_length=50, verbose_name='Токен бота'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='name_bot',
            field=models.CharField(default='', max_length=30, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='pay_token',
            field=models.CharField(default='', max_length=30, verbose_name='Токен оплаты'),
        ),
        migrations.AlterField(
            model_name='bzuusers',
            name='carbohydrates',
            field=models.IntegerField(verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='bzuusers',
            name='fats',
            field=models.IntegerField(verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='bzuusers',
            name='proteins',
            field=models.IntegerField(verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='breast_after',
            field=models.FloatField(blank=True, null=True, verbose_name='Отправка замеров груди ПОСЛЕ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='breast_before',
            field=models.FloatField(blank=True, null=True, verbose_name='Отправка замеров талии ДО'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='femur_after',
            field=models.FloatField(blank=True, null=True, verbose_name='Отправка замеров груди ПОСЛЕ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='femur_before',
            field=models.FloatField(blank=True, null=True, verbose_name='Отправка замеров бедер ДО'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist_after',
            field=models.FloatField(blank=True, null=True, verbose_name='Отправка замеров груди ПОСЛЕ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist_before',
            field=models.FloatField(blank=True, null=True, verbose_name='Отправка замеров груди ДО'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight_after',
            field=models.FloatField(blank=True, null=True, verbose_name='Отправка замеров груди ПОСЛЕ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight_before',
            field=models.FloatField(blank=True, null=True, verbose_name='Отправка замеров веса ДО'),
        ),
        migrations.AlterField(
            model_name='users',
            name='bzu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal_area.bzuusers'),
        ),
        migrations.AlterField(
            model_name='users',
            name='measurement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal_area.measurement'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal_area.photo'),
        ),
    ]
